Repository spatialos/platform-sdk-csharp, pull requests merged in 2019-07, with the labels that each got.

#35 Parse credentials in from environment for server workers.
  apis/platform_common/Credential.cs
Labels: jira/no-ticket, size/M

#36 Regenerate SDK from upstream
  .gitignore
  WORKSPACE
  apis/deployment_v1alpha1/BUILD
  apis/deployment_v1alpha1/Deployment.cs
  apis/deployment_v1alpha1/DeploymentGrpc.cs
  apis/playerauth_v2alpha1/BUILD
  apis/playerauth_v2alpha1/PlayerAuth.cs
  apis/serviceaccount_v1alpha1/BUILD
  scripts/generateapis.sh
Labels: jira/no-ticket, size/XXL

#38 Fix auto-initialisation logic of credentials
  apis/platform_common/Credential.cs
Labels: jira/no-ticket, size/S

#40 Fix nightly build
  scripts/generateapis.sh
  scripts/includes/os.sh
  scripts/nightly.sh
  scripts/premerge.sh
  scripts/release.sh
  scripts/runtests.sh
Labels: jira/no-ticket, size/M

#24 Merge SDK dependencies into one assembly
  apis/apis.csproj
  scripts/release.sh
Labels: jira/no-ticket, size/M

#41 WF-1242 Add sample implementation of PlayerIdentityToken verification code in authentication flow example
  examples/BYOAuthFlow/Program.cs
  examples/README.md
Labels: jira/WF, size/S
